### ISSUE TITLE
Is it legal to have symsrv.dll redistributed?

### ISSUE THREAD

**Issue by a-cristi** [ShaneK2/inVtero.net#4]
This might be a non-issue, but I want to be sure.

Is it legal to have symsrv.dll redistributed like this? The same goes for obtaining and using the .pdbs in a situation like this.

**Comment by K2** [comment]
Hey Cristi I'll take a look at the fine print I thought it was with the new set of free VS community.  Thanks.

**Comment by K2** [comment]
I'll keep reviewing how other tools handle this, however, were relatively OK based on; https://github.com/jrfonseca/drmingw/issues/17

**Comment by K2** [comment]
Closed as per long discussions regarding the specific use of these DLL's seems fine in a number of other packages and also from the linked discussion;

f my knowledge, the closest description of how Microsoft intends DbgHelp and SymSrv to be redistributed is https://msdn.microsoft.com/en-us/library/windows/desktop/ms679294.aspx which says

The redistribution policies for these included DLLs were specifically designed to make it as easy as possible for people to include these files in their own packages and releases.
and https://msdn.microsoft.com/en-us/library/windows/desktop/ff805116.aspx which says

When using DbgHelp, the best strategy is to install a copy of the library from the Debugging Tools For Windows package in the application directory logically adjacent to the software that calls it. If Symbol Server and Source Server are also needed, then both SymSrv.dll and SrcSrv.dll must be installed in the same directory as DbgHelp.dll, as DbgHelp will only call these DLLs if they share the same directory with it. (Note that DbgHelp will not call these two DLLs from the standard search path.) This helps prevent the usage of mismatched DLLs; likewise, it also improves security overall."

**Comment by a-cristi** [comment]
Awesome! Thanks for the quick reply.
